### ISSUE TITLE
Proposal: Disposer

### ISSUE THREAD

**Issue by yjbanov** [google/quiver-dart#137]
Our team found it useful to have a utility that aggregates various types of subscriptions (StreamSubscription, StreamSink (usually StreamController), as well as custom cleanup functions) and clean them up all at once at a certain moment. A popular use-case is a UI component being destroyed while still fetching things from the server. Another use-case I can see is cleaning-up when things go wrong, e.g. closing sockets/files when errors happen.

Proposed API:

```
class Disposer {
  Disposer();

  /// [disposable] will be "disposed of" when the [dispose] method is called. The
  /// meaning of "dispose" depends on the type of disposable, which can be one of:
  ///
  /// - [StreamSubscription], disposer calls `cancel()` when disposing
  /// - [StreamSink], disposer calls `close()` when disposing
  /// - [Function] that takes no arguments and returns either `null` or a [Future]. This
  /// function is called by the disposer as is. The implementation is defined by the user.
  void add(dynamic disposable);

  /// Disposes of all disposables [add]ed to `this` disposer.
  ///
  /// The returned future completes when all disposables are successfully disposed of.
  Future dispose();

  /// Sets a [trigger] used as a signal to dispose everything collected so far. Can be used
  /// as an alternative to calling [dispose] directly.
  set trigger(Future t);
}
```

**Comment by alexeieleusis** [comment]
There is a public implementation now at https://github.com/dart-lang/angular_components/blob/master/lib/src/utils/disposer/disposer.dart
Could it be imported/copied here? It seems to be stable enough that is unlikely for it to change, once is here it can be used from flutter/angular/butterfly/etc.
And once here it can be integrated with static analysis tools like requested here https://github.com/dart-lang/linter/issues/285

**Comment by matanlurey** [comment]
This probably doesn't belong in quiver. 

Angular at least would prefer not to require a dependency on it for the runtime; I'd prefer something like `pkg/dispose`, but I'll wait to see what someone like @kevmoo thinks.

**Comment by cbracken** [comment]
I'd definitely prefer not to add entirely new areas of functionality to quiver.

**Comment by yjbanov** [comment]
Whatever use-cases there were back in 2014 that prompted me to file this feature request are no longer relevant to me personally. Unless someone else champions this feature, I'm ok with closing.

**Comment by alexeieleusis** [comment]
@matanlurey where is this pkg/dispose you mention? Or your suggestion is to create a new one?

The reason I am interested in this is because it is a common pattern in my team to add stream controllers and subscriptions to the mentioned disposer and that disables warnings to close or cancel them respectively, but the disposer could be not disposed and memory leaks potentially can be there.

**Comment by matanlurey** [comment]
We do not have this package, I'll chat with the Dart team about creating one - otherwise Angular will be very reluctant on taking on this dependency.

That being said, this doesn't seem appropriate for a linter, as it's package specific. Any team could create a `MyStreamCleaner` and not get lint warnings. I'd prefer to wait for the proposed new analyzer plugins - then pkg/dipose (or w/e is created) could publish its own analysis plugin.

**Comment by matanlurey** [comment]
@yjbanov Feel free to close this issue, we can continue discussions elsewhere if needed.
