### ISSUE TITLE
Question re/ emptyToNull removal

### ISSUE THREAD

**Issue by ochafik** [google/quiver-dart#340]
Could someone explain the rationale behind that removal?

We keep getting cases like

```dart
get foo => emptyToNull(costlyOrJustLengthy.expression());
```

Which isn't pretty without emptyToNull:

```dart
get foo {
  const x = costlyOrJustLengthy.expression();
  return x == '' ? null : x;
}
```

**Comment by cbracken** [comment]
Mostly the rationale was that the introduction of the null-aware operators eliminated the need for `nullToEmpty()` which called into question whether it was worth maintaining `emptyToNull()`.

Rationale came down to:
* there was only a single use in the Google codebase, and the argument was a variable rather than a complex expression.
* for the most part `s == '' ? null : s` is the preferred solution. There's something to be said for encouraging a consistent solution, even at the cost of an additional line of code, rather than two different solutions (one of which adds the overhead of a method call -- subject to compiler inlining, possibly) depending on the surrounding code.

I realise that second point sounds fairly prescriptive and it's possible that that played into the decision to kill it, at least internally. I'm fine bringing it back if you've got a codebase that's improved by its use.
