### ISSUE TITLE
zip for iterables that don't have the same type

### ISSUE THREAD

**Issue by gazialankus** [google/quiver-dart#489]
`zip` is great, but it would not work if you wanted to zip a `<String>[]` and an `<int>[]`. There is also [`IterableZip`](https://pub.dartlang.org/documentation/collection/latest/collection/IterableZip-class.html) from `package:collection`, which has the same issue. [Here in StackOverflow](https://stackoverflow.com/a/53158372/679553) is an implementation that can zip two lists with different types. 

Please let me know if I'm missing something. If what I said makes sense, please let me know and I can send a PR that adds this new zip. What would be the name of this new zip? (zipDifferent, zip2, ...)

**Comment by cbracken** [comment]
What would the generic type `T` of the resultant `List<T>` be for such a function? If I'm understanding the request right, the only possible general answer would be `dynamic`, though I suppose you could have the caller specify some common superclass/interface. Such a function would have pretty poor ergonomics, since the user would be left to check/cast the values each time they're fetched.

**Comment by gazialankus** [comment]
The return type is the `List<T3>`, where `T3` is given by the caller, in the StackOverflow answer that I referred to:
 
```
List<T3> zipList<T1, T2, T3>(List<T1> l1, List<T2> l2, T3 Function(T1, T2) zipper) {
  if (l1.isEmpty) throw ArgumentError.value(l1, "l1", "input list cannot be empty");
  if (l1.length != l2.length) throw ArgumentError("Two lists must have the same length");
  var result = List<T3>(l1.length);
  for(var i = 0; i < l1.length; i++) {
    result.add(zipper(l1[i], l2[i]));
  }
  return result;
}
```

We can call `final myList = zipList<int, int, String>([1, 2], [3, 4], (a, b) => "$a, $b")` and `myList` would be a `List<String>`, right? Does it have to be `dynamic` in this example? It's not very different than the `map` function of list, in which you specify the returned iterable's type parameter when you're calling it.

**Comment by cbracken** [comment]
Sorry I think I misunderstood your original proposal, which I'd assumed to be like [zip](https://github.com/google/quiver-dart/blob/master/lib/src/iterables/zip.dart), which simply interleaves a set of iterables into a new iterable where the returned iterable's nth element contains the nth element from each of the input iterables. 

It sounds like what you're after is effectively [Iterable.fold](https://api.dartlang.org/stable/2.6.0/dart-core/Iterable/fold.html) or [Iterable.reduce](https://api.dartlang.org/stable/2.6.0/dart-core/Iterable/reduce.html) but for the specific case of two `List`s?

That sounds pretty specific. I think there are two things you'd want to do to make this general enough to make sense here. The first is easy: use `Iterable` instead of `List`. The second is to avoid arbitrarily limiting this to two input lists -- why two and not three, or four, or n? If Dart supported variadic functions, we'd be able to do this gracefully, but it doesn't, so we're back to an `Iterable` of `Iterable`s like we have in `zip` today, with all the issues described in my original reply. Even if we were willing to accept it being dynamic, it would be sort of pointless, since if you're using dynamic, then you'd just write `zip(iterables).map(zipper)` and you'd have the same behaviour.

**Comment by gazialankus** [comment]
Ok since it's been a while only now I fully comprehend the situation :) 

Yes, it seems what I wanted was not exactly what `zip` is. I didn't know what `zip` is. I simply wanted to map multiple lists into a single list, with all of which having the same length. Then I arrived at that SO question that wanted the same, and that answer suggested a version of "`zip`". I agree that it's not a great match. 

I found the code that I created when I asked for this. Could as well use `.map()` instead. 

```
      final Iterable<FlowReading> flowReadings =
          querySnapshot.documents.map((shot) => FlowReading.fromMap(shot.data));

      final rows = zipIterable3(
          List<int>.generate(querySnapshot.documents.length, (i) => i),
          flowReadings,
          querySnapshot.documents, (i, flowReading, shot) {
        return buildFlowReadingLine(i++, flowReading, shot.reference, context);
      }).toList();
```

Obviously you are right about this not scaling, which is supported by my "`zipIterable3`". I'm not advocating for this anymore, so I'll just close this. Thank you for your time @cbracken!

**Comment by cbracken** [comment]
Thanks! And sorry about the amount of time it took to get to this. This is a 20% project for the authors and we've been pretty busy in the last year :)

**Comment by goertzenator** [comment]
For those landing here looking for zips of different types, see below.

I was having a hard time with `IterableZip` and truly needed `zip2` below.  Copilot was happy to write bigger versions for me so I let it keep on going. :)  If that's still not enough you can nest them.  These zips are for `List` and not `Iterable`: I am too new to Dart to go there right now.

I know this looks a bit ugly, but some other languages including Haskell do exactly this.


``` dart
// import 'dart:math';

List<(T1, T2)> zip2<T1, T2>(List<T1> l1, List<T2> l2) {
  final len = [l1.length, l2.length].reduce(min);
  return [for (int i = 0; i < len; i++) (l1[i], l2[i])];
}

List<(T1, T2, T3)> zip3<T1, T2, T3>(List<T1> l1, List<T2> l2, List<T3> l3) {
  final len = [l1.length, l2.length, l3.length].reduce(min);
  return [for (int i = 0; i < len; i++) (l1[i], l2[i], l3[i])];
}

List<(T1, T2, T3, T4)> zip4<T1, T2, T3, T4>(
    List<T1> l1, List<T2> l2, List<T3> l3, List<T4> l4) {
  final len = [l1.length, l2.length, l3.length, l4.length].reduce(min);
  return [for (int i = 0; i < len; i++) (l1[i], l2[i], l3[i], l4[i])];
}

List<(T1, T2, T3, T4, T5)> zip5<T1, T2, T3, T4, T5>(List<T1> l1, List<T2> l2,
    List<T3> l3, List<T4> l4, List<T5> l5) {
  final len = [l1.length, l2.length, l3.length, l4.length, l5.length].reduce(min);
  return [for (int i = 0; i < len; i++) (l1[i], l2[i], l3[i], l4[i], l5[i])];
}

List<(T1, T2, T3, T4, T5, T6)> zip6<T1, T2, T3, T4, T5, T6>(
    List<T1> l1, List<T2> l2, List<T3> l3, List<T4> l4, List<T5> l5, List<T6> l6) {
  final len = [l1.length, l2.length, l3.length, l4.length, l5.length, l6.length].reduce(min);
  return [for (int i = 0; i < len; i++) (l1[i], l2[i], l3[i], l4[i], l5[i], l6[i])];
}

List<(T1, T2, T3, T4, T5, T6, T7)> zip7<T1, T2, T3, T4, T5, T6, T7>(
    List<T1> l1, List<T2> l2, List<T3> l3, List<T4> l4, List<T5> l5, List<T6> l6, List<T7> l7) {
  final len = [l1.length, l2.length, l3.length, l4.length, l5.length, l6.length, l7.length].reduce(min);
  return [for (int i = 0; i < len; i++) (l1[i], l2[i], l3[i], l4[i], l5[i], l6[i], l7[i])];
}

List<(T1, T2, T3, T4, T5, T6, T7, T8)> zip8<T1, T2, T3, T4, T5, T6, T7, T8>(
    List<T1> l1, List<T2> l2, List<T3> l3, List<T4> l4, List<T5> l5, List<T6> l6, List<T7> l7, List<T8> l8) {
  final len = [l1.length, l2.length, l3.length, l4.length, l5.length, l6.length, l7.length, l8.length].reduce(min);
  return [for (int i = 0; i < len; i++) (l1[i], l2[i], l3[i], l4[i], l5[i], l6[i], l7[i], l8[i])];
}

List<(T1, T2, T3, T4, T5, T6, T7, T8, T9)> zip9<T1, T2, T3, T4, T5, T6, T7, T8, T9>(
    List<T1> l1, List<T2> l2, List<T3> l3, List<T4> l4, List<T5> l5, List<T6> l6, List<T7> l7, List<T8> l8, List<T9> l9) {
  final len = [l1.length, l2.length, l3.length, l4.length, l5.length, l6.length, l7.length, l8.length, l9.length].reduce(min);
  return [for (int i = 0; i < len; i++) (l1[i], l2[i], l3[i], l4[i], l5[i], l6[i], l7[i], l8[i], l9[i])];
}
```
