### ISSUE TITLE
countdown.remaining does not have expected behaviour

### ISSUE THREAD

**Issue by Vanethos** [google/quiver-dart#495]
```dart
test("Countdown remaining", () async {
      var countdownTime = 10;
      CountdownTimer(
          Duration(seconds: countdownTime), Duration(seconds: 1))
          .listen((countdown) => print(countdown.remaining.inSeconds));

      await Future.delayed(Duration(seconds: 12));
    });
```

I would expect the following to print: 

```
9
8
7
6
5
4
3
2
1
0
```

However, it is printing 

```
8
7
6
5
4
3
2
1
0
0
```

Note that 0 is printed twice.

I see that this is because the statement:

`Duration get remaining => _duration - _stopwatch.elapsed;`

Is printed a little after the second has passed, resulting in the following for the first print:

`_duration: 0:00:10.000000, _stopwatch.elapsed: 0:00:01.004716, difference: 0:00:08.995278`

Here the seconds will be 8, despite the fact that the milliseconds are very close to 1 second. This can be due to the threshold, as highlighted in `_tick`

**Comment by cbracken** [comment]
Under the hood, this class makes use of [Timer.periodic](https://api.dartlang.org/stable/2.2.0/dart-async/Timer/Timer.periodic.html) which does not guarantee to-the-millisecond precision. If you used `inMilliseconds` my guess would be that you'd be within a few milliseconds of 9, 8, 7, etc.

One option might be:

```
CountdownTimer(
  Duration(seconds: countdownTime),
  Duration(seconds: 1),
).listen((countdown) => print((countdown.remaining.inMilliseconds / 1000).round()));
```

This still won't necessarily guarantee exact timing, since with enough effort, you can still stall the event loop handling timer events, but it's probably good enough for something user-facing.

Does that help?

**Comment by Vanethos** [comment]
Yup! This is exactly what I was thinking.

If I can offer my opinion, more than just the documentation, I as a new user this would be a convenient helper method (though it is easy enough to implement)
