### ISSUE TITLE
Why not be part of the dart language itself

### ISSUE THREAD

**Issue by timnew** [google/quiver-dart#576]
Quiver is great, it makes working with Dart a lot easier.

But I just don't understand, as from my point of view, most of the feature that provided by this library should be just part of the language itself. Why we need an additional library to achieve some most basic tasks? Especially, when the library is created and maintained by the same company who created the language.

Just wondering is it possible to get the library merged into `dart:core` in the future?

**Comment by yjbanov** [comment]
Filing a feature request on https://github.com/dart-lang/sdk/ or https://github.com/dart-lang/language/ might be a good way to start that conversation. I think it would be most effective to file a feature request for each specific function rather than to ask to merge all of quiver in one go. You'd have to get a buy-in from the Dart team and find an owner to implement and roll out the new feature (which could be you; it's open-source!).

Some things from quiver did actually make it into the standard libraries, and so we deprecated/removed them from quiver, e.g. https://github.com/google/quiver-dart/pull/521.

**Comment by cbracken** [comment]
Several things in quiver now have equivalent or better APIs in the core libraries. Examples include `Future.forEach` and `Future.doWhile` as alternatives to Quiver's `forEachAsync` and `doWhileAsync`, the `??` operator as an alternative to `firstNonNull`, and nullable/non-nullable types as an alternative to the `Optional` class.

As @yjbanov suggests, the best approach is to file (or upvote) feature requests at https://github.com/dart-lang/sdk. Quiver has some useful utilities, but also some fairly old cruft. Handling this as a set of case-by-case requests is probably best.

**Comment by cbracken** [comment]
Unrelated but looking at those logs from 2013, it's surprising how long this package has been around, I see patches I landed for compatibility with Dart SDK 0.6. A fair bit has changed in the interim.
