### ISSUE TITLE
Add fromValue factory constructor to the Optional

### ISSUE THREAD

**Issue by BreX900** [google/quiver-dart#586]
This would save lines of code
Example:
`snaphost.data != null ? Optional.fromNullable(snaphost.data) : null`
`Optional.fromValue(snaphost.data)`

```
/// Constructs an Optional of the given [value].
///
/// If [value] is null, returns [null].
factory Optional.fromValue(T value) {
  return value != null ? Optional.fromNullable(value) : null;
}
```

**Comment by cbracken** [comment]
Thanks for filing -- this is working as intended.

Generally, you shouldn't mix `Optional` and null values. Instead just use `Optional.fromNullable(snapshot.data)` if `snapshot.data` can be null.

At usage sites, if it would be a programmer error if the optional were null just use `Optional.value` directly. You'll get a `StateError` thrown if it's null since an invariant is being violated.

If you're unsure if a value is null you have a few options:
  * Check `Optional.isPresent` or `Optional.isNotPresent` then use the value
  * Use `Optional.ifPresent((value) { ... })` which will invoke the lambda or function you pass in if the Optional holds a (non-null) value.
  * Use `Optional.or()` to provide a default, like `optional.or('n/a')`

Let me know if you've got any questions!
