### ISSUE TITLE
Constant `BiMap` constructor?

### ISSUE THREAD

**Issue by om-ha** [google/quiver-dart#699]
In the example below, compare the constant Map `_ColorEnumStringMap` against the non-constant BiMap `_ColorEnumStringBimap`

So is it possible to provide a constant constructor for the `BiMap` class?
<sub>with constant `.inverse`? 😅</sub>

```dart
import 'package:quiver/collection.dart';

enum ColorEnum {
  Red,
  Blue,
}

extension ColorEnumExtension on ColorEnum {
  /// Bi-directional map between ColorEnum and its underlying String value
  static const Map<ColorEnum, String> _ColorEnumStringMap = {
    ColorEnum.Red: 'Red',
    ColorEnum.Blue: 'Blue',
  };

  /// Bi-directional map between ColorEnum and its underlying String value
  static final BiMap<ColorEnum, String> _ColorEnumStringBimap = BiMap<ColorEnum, String>()
    ..addAll({
      ColorEnum.Red: 'Red',
      ColorEnum.Blue: 'Blue',
    });

  /// Returns null if no enum entry is found in the BiMap
  String? get string {
    return _ColorEnumStringBimap[this];
  }

  /// Returns null if string is not associated with an enum in the BiMap (or the entry is missing)
  static ColorEnum? fromString({required String string}) {
    return _ColorEnumStringBimap.inverse[string];
  }
}
```

Extrapolated from this flutter issue: https://github.com/dart-lang/language/issues/1563#issuecomment-1127504086

**Comment by cbracken** [comment]
I assume this would be something like a `BiMap.from(Map<K, V> map)` constructor?

BiMap stores both the [forward map and its inverse](https://github.com/google/quiver-dart/blob/524f33ddaa416af6e616a2f86edac44a5647ceed/lib/src/collection/bimap.dart#L47-L48) internally. Since we'd need to generate the inverse in the constructor, and there's no way to do that in a const context, I don't think this would be possible, as the private constructor does right now. That would be pretty cumbersome API I'd think, unfortunately.
