### ISSUE TITLE
Zip like in Swift

### ISSUE THREAD

**Issue by intonarumori** [google/quiver-dart#733]
In Swift you can zip together two lists with different element types.
https://developer.apple.com/documentation/swift/zip(_:_:)

Would this be possible in Dart?
Maybe using the tuple package:
https://pub.dev/packages/tuple

Thanks.

**Comment by cbracken** [comment]
That's a bit semantically different from what quiver's [zip](https://github.com/google/quiver-dart/blob/master/lib/src/iterables/zip.dart) currently does, since it emits an `Iterable` of `List` and lists are of a single generic type. 

I imagine it would be pretty straightforward to implement something specific to a given tuple arity such as 2 like in the Swift case above, but I don't think we'd be likely to take it for Quiver since (a) we don't want to add any non-dev dependencies on other packages and (b) if Dart ever adds support for macros, that's probably how we'd do it, assuming macros support passing a set of generics as a macro input. If Dart gets to that point, I think it would be a reasonable addition, though we'd need a new name for it.

In the meantime, you could always create a new package for something like that and link to it from this issue for visibility.

/cc @yjbanov who may have thoughts.
